function [ options ] = conFigureOptions( setName )
% conFigureOptions  -  Load a set of options for conFigure
%
% Create perminent sets of options for conFigure
% Use the "Default" options set as a tempate
%
% 'Width' - Width of the figure in [Units].
% 'Height' -  Height of the figure in [Units].
% 'Separation' - Separation between adjacent plots in [Units].
% 'FigPadding', - Padding around the figure in [Units]; [left bottom right top]
% 'Units' - Units used for the above options; i.e. 'centimeters'
% 'XRatios' - Ratios of relative column widths
% 'YRatios' - Ratios of relative row heights
% 'UniformPlots' - Make all plots the size of the smallest; true/false
%                  (can make figure tidier and comparison between plots
%                  easier)
% 'Labels', - Add labels to all the plots in the figure; true/false
% 'LabelOrder' - String array of plot labels; i.e. ["a" "b" "c" "d"]
% 'LabelEnds' - 1x2 String array to suround plot labels; i.e. ["(",")"]
%


    if( strcmpi(setName,'Default'))
        
                options = struct('Width',16,...
                         'Height',16,...
                         'Units','centimeters',...
                         'Separation',0.3,...
                         'XRatios',[],...
                         'YRatios',[],...
                         'FigPadding',[0,0,0,0],...
                         'UniformPlots', false,...
                         'Labels',true,...
                         'LabelOrder',["a","b","c","d","e","f","g","h","i","j","k","l","m","n","o","p"],...
                         'LabelEnds',["(",")"]);        
                        
    elseif( strcmpi(setName,'PhysicalReviewSingleColumn'))
        
                options = struct('Width',8.6,...
                         'Height',8.6,...
                         'Units','centimeters',...
                         'Separation',0.3,...
                         'XRatios',[],...
                         'YRatios',[],...
                         'FigPadding',[0,0,0,0],...
                         'UniformPlots', false,...
                         'Labels',true,...
                         'LabelOrder',["a","b","c","d","e","f","g","h","i","j","k","l","m","n","o","p"],...
                         'LabelEnds',["(",")"]);   
        
    elseif( strcmpi(setName,'PhysicalReviewDoubleColumn'))
        
                options = struct('Width',17.8,...
                         'Height',17.8,...
                         'Units','centimeters',...
                         'Separation',0.3,...
                         'XRatios',[],...
                         'YRatios',[],...
                         'FigPadding',[0,0,0,0],...
                         'UniformPlots', false,...
                         'Labels',true,...
                         'LabelOrder',["a","b","c","d","e","f","g","h","i","j","k","l","m","n","o","p"],...
                         'LabelEnds',["(",")"]);     
    
    elseif( strcmpi(setName,'ThesisFullWidth'))
        
                options = struct('Width',15,...
                         'Height',15,...
                         'Units','centimeters',...
                         'Separation',0.3,...
                         'XRatios',[],...
                         'YRatios',[],...
                         'FigPadding',[0,0,0,0],...
                         'UniformPlots', false,...
                         'Labels',true,...
                         'LabelOrder',["a","b","c","d","e","f","g","h","i","j","k","l","m","n","o","p"],...
                         'LabelEnds',["(",")"]);   
    end
end

