function [ figOptions, axis1Options, dataOptions, axis2Options ] = proPlotOptions( setName )
% proPlotOptions  -  Load a set of options for proPlot
%
% Create perminent sets of options for proPlot
% Use the "Default" options set as a tempate
%
% figOptions - set the options relevant to the whole figure
%   'Width' - width of the plot in [Units].
%   'Height'- height of the plot in [Units].
%   'Padding' - Pad the figure [left,bottom,right,top] in [Units];
%   'Units' - Units for the above options; i.e. 'centimeters'
%   'LabelString' - Label for the plot; i.e. '(a)'
%   'LabelFontSize' - Label font size (in points)
%   'LabelInterpreter' - Label interpreter, i.e. 'latex'
%   'Color' - background color of the figure
%   'InstaPlot' - Whether to automatically plot/replot after any change
%
% axis1Options - Set the options of axis1
% axis2Options - Set the options of axis2
%   axis options are mostly set using the exact name of the property on the
%   axis object. There are a few exceptions;
%       'XLabelText' - Sets the text for the x axis label (and similar for y and z axis labels)
%       'Interpreter' - Sets the interpreter for most text on the axis
%       'Color' - Not an exception but a note that this option sets the
%               background color for the axis - If using two axes this
%               should be set to 'none' to make sure you can see data on
%               both axes. Set teh figure color to change background color.
%
% dataOptions - Set the options for a particular set of data
%   Data options are mostly set using the exact name of the property on the
%   i.e. using Color on a line plot will change the Color of the line,
%       however on a scatter plot you will need to use CData instead.
%   plot object. There are a few exceptions.
%       'x','y','z' - Set the data. (If not required, leave it unset with [])
%       'PlotType' - Sets how the data will be plotted. Can be one of 
%           {'line', 'scatter', 'fill', 'pcolor', 'surf', 'annotation', 'image'}
%       'Axis' - Sets which axis to plot the data on (can be either 1 or 2)
%       'DownSample2DPlot' - Sets a max number of pixels for pcolor and surf plots; [width height].
%   For 'PlotType' 'annotation' options:
%        'AnnotationType' - Sets the type of annotation, use "help annotation" for more information
%        'String'         - If the annotation type requires a string
%   For 'PlotType' 'image' option:
%        'ImageFile' - String containing file name of the image file to
%           load i.e. 'imageFile.png'.
%

    if( strcmpi(setName,'Default'))
        
        dataOptions = struct('x',[],...
                             'y',[],...
                             'z',[],...
                             'PlotType','line',...
                             'Axis',1,...
                             'LineWidth',1,...
                             'EdgeColor','none');

        axis1Options = struct('XLabelText','$x$ axis label',...
                             'YLabelText','$y$ axis label',...
                             'ZLabelText','$z$ axis label',....
                             'XGrid', 'off',...
                             'YGrid', 'off',...
                             'ZGrid', 'off',...
                             'TickDir','out',...
                             'FontSize',9,...
                             'LabelFontSizeMultiplier', 1.2,...
                             'LineWidth',1,...
                             'ColorOrder',[  68, 119, 170;...      % blue
                                            102, 204, 238;...      % cyan
                                            34, 136,  51;...      % green
                                            204, 187,  68;...      % yellow
                                            238, 102, 119;...      % red
                                            170,  51, 119;...      % purple
                                            187, 187, 187]/255,... % grey
                             'Color', 'none',...
                             'Box','off',...
                             'Interpreter','latex',...
                             'TickLabelInterpreter', 'latex');

        axis2Options = [];

        figOptions = struct('Padding',[0,0,0,0],... %pad the figure [left,bottom,right,top] in Units
                            'Width',15.0,... % in Units
                            'Height',15.0,... % in Units
                            'Units','centimeters',...                              
                            'LabelString','',... % the label next to the figure
                            'LabelFontSize',12,...
                            'LabelInterpreter','latex',...
                            'InstaPlot',false,... % whether to automatically plot/replot after any change
                            'Color',[1 1 1]); % background of figure 
        
                        
    elseif( strcmpi(setName,'DefaultImage'))
        
        dataOptions = struct('x',[],...
                             'y',[],...
                             'z',[],...
                             'PlotType','line',...
                             'Axis',1,...
                             'LineWidth',2,...
                             'EdgeColor','none');

        axis1Options = struct('XLabelText','',...
                             'YLabelText','',...
                             'ZLabelText','',....
                             'XGrid', 'off',...
                             'YGrid', 'off',...
                             'ZGrid', 'off',...
                             'XTick',[],...
                             'YTick',[],...
                             'XColor', 'none',...
                             'YColor', 'none',...
                             'TickDir','out',...
                             'FontSize',10,...
                             'LabelFontSizeMultiplier', 1.2,...
                             'LineWidth',1,...
                             'ColorOrder',[  68, 119, 170;...      % blue
                                            102, 204, 238;...      % cyan
                                            34, 136,  51;...      % green
                                            204, 187,  68;...      % yellow
                                            238, 102, 119;...      % red
                                            170,  51, 119;...      % purple
                                            187, 187, 187]/255,... % grey
                             'Box','off',...
                             'Interpreter','latex');

        axis2Options = [];

        figOptions = struct('Padding',[0,0,0,0],... %pad the figure [left,bottom,right,top] in Units
                            'Width',15.0,... % in Units
                            'Height',15.0,... % in Units
                            'Units','centimeters',...                              
                            'LabelString','',... % the label next to the figure
                            'LabelFontSize',12,...
                            'LabelInterpreter','latex',...
                            'InstaPlot',false,... % whether to automatically plot/replot after any change
                            'Color',[1 1 1]); % background of figure 
        
        
    end
end

